version: '3.4'

services:
  blazorproject.server:
       image: ${DOCKER_REGISTRY-}blazorprojectserver
       build:
          context: .
          dockerfile: BlazorProject/Server/Dockerfile
       ports:
          - "8080:80"
       environment:
          ConnectionStrings_DefaultConnection: "Host=Asus123;Database=postgres;Username=postgres;Password=postgres"
       depends_on:
              - db
  db:
       container_name: db
       image: postgres:12
       ports:
         - "5432:5432"
       environment:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
       volumes:
         - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
   
